FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements_test.txt /app/

RUN pip install -r requirements.txt -r requirements_test.txt

COPY app /app/app
COPY tests /app/tests

CMD ["pytest", "tests", "--html=/tmp/report.html"]